display: flex;
flex-direction: column;
justify-content: flex-end;
align-items: flex-start;


infoTextArray = [
    { hilite: "grid", text: "The grid is a 12 x 18 table of 50x50px cells." },
    { hilite: "regions", text: "Game components are generated by defining regions on the grid." },
    { hilite: "indexCell", text: "Regions are located via their indexCell which has row and column attributes." },
    { hilite: "attributes", text: "Regions are further defined by width, height and merge attributes." },
    { hilite: "width and height", text: "width and height define size (in the number of cells wide or tall)." },
    { hilite: "Merge", text: "Merge defines whether a single spanned cell creates the region or a series of individual cells." }
];
